public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 2");
        dog = dog + 4;
        cat = cat + 4;
        paper = paper + 4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 3");
        dog = dog - 3.5;
        cat = cat - 1.6;
        paper = paper - 7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        System.out.println("Задача 6");
        var weightOneBoxer = 78.2;
        var weightTwoBoxer = 82.7;
        var totalWeight = weightOneBoxer + weightTwoBoxer;
        System.out.println(totalWeight);
        var differenceWeight = weightTwoBoxer - weightOneBoxer;
        System.out.println(differenceWeight);
        System.out.println("Задача 7");
        var remainderWeightDivision = weightTwoBoxer % weightOneBoxer;
        System.out.println(remainderWeightDivision);
        System.out.println("Задача 8");
        var totalTime = 640;
        var hoursOneEmployee = 8;
        var employees = totalTime / hoursOneEmployee;
        System.out.println("Всего работников в компании " + employees + " человек");
        employees = employees + 94;
        totalTime = employees * hoursOneEmployee;
        System.out.println("Если в компании работает " + employees +  " человек, то всего " + totalTime + " часов работы может быть поделено между сотрудниками");
    }
}